spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    url: ${DB_URL}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  application:
    security:
      jwt:
        secret:
          access: ${ACCESS_TOKEN:defaultAccessTokenBase64}
          refresh: ${REFRESH_TOKEN:defaultRefreshTokenBase64}

  mail:
    host: localhost
    port: 1025
    username: hello@example.com
    password: hello
    protocol: smtp
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connection-timeout: 50000
        timeout: 3000
        write-timeout: 5000

hostname: localhost:8080