spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:auth_service_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:auth_service_db}
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123}

  application:
    security:
      jwt:
        secret:
          access: ${ACCESS_TOKEN}
          refresh: ${REFRESH_TOKEN}

  mail:
    host: localhost
    port: 1025
    username: hello@example.com
    password: hello
    protocol: smtp
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connection-timeout: 50000
        timeout: 3000
        write-timeout: 5000

hostname: localhost:8080