apiVersion: apps/v1
kind: Deployment
metadata:
  name: taxi-user-service
  labels:
    app: taxi-user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taxi-user-service
  template:
    metadata:
      labels:
        app: taxi-user-service
    spec:
      containers:
        - name: taxi-user-service
          image: yahim202002/simple-taxi-user-service:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: taxi-user-service-config
            - secretRef:
                name: taxi-user-service-secret
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
